language: go
go:
  - 1.9.x
  - 1.10.x

go_import_path: github.com/boris-lenzinger/simple-learning
  github.com/fatih/color

install: go install github.com/boris-lenzinger/simple-learning

script:
  - go vet github.com/boris-lenzinger/simple-learning
  - test -z "$(go fmt ./...)" # fail if not formatted properly
  - godog -f progress
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
