language: go
go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x

go_import_path: github.com/boris-lenzinger/simple-learning/src/lib

install: go install github.com/boris-lenzinger/simple-learning/src/lib

script:
  - go vet github.com/boris-lenzinger/simple-learning/src/lib
  - test -z "$(go fmt ./...)" # fail if not formatted properly
  - godog -f progress
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
